### PR TITLE
Update spi_api.c

### LINKED ISSUE #36: SD card related APIs seem to be broken on Artemis boards
### Description of defect
Some days ago i closed #34 as i by getting back the size and other data of my SD card, i thought it will work. So i ported my project from the MAX32630FTHR board to Artemis Thing Plus. The core functionality of the project is datalogging on the fly. When using the Artemis board at the end of the recording session all i get is an erased, empty SD card.
While on the MAX32630FTHR i always get my files as expected.
This has led me to test Mbed's SD examples once again on the Artemis Thing Plus. It seems, the board can somehow get the size of the SD card, despite it fails to initialize/deinitialize the SDBlockDevice. Pretty strange!

#### Target(s) affected by this defect ?
Artemis Thing Plus

#### Toolchain(s) (name and version) displaying this defect ?
ARMC 6.14

#### What version of Mbed-os are you using (tag or sha) ?

Mbed OS 6.3.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
Mbed Studio V1.2.1

#### How is this defect reproduced ? 
Try this code:

```
#include "mbed.h"
#include "SDBlockDevice.h"

#if TARGET_MAX32630FTHR
#include "lib/max32630fthr/max32630fthr.h"
MAX32630FTHR pegasus(MAX32630FTHR::VIO_3V3);
#endif

Timer timer;
// Instantiate the SDBlockDevice by specifying the SPI pins connected to the SDCard
// socket. The PINS are:
//     MOSI (Master Out Slave In)
//     MISO (Master In Slave Out)
//     SCLK (Serial Clock)
//     CS (Chip Select)
SDBlockDevice sd(MBED_CONF_SD_SPI_MOSI, MBED_CONF_SD_SPI_MISO, MBED_CONF_SD_SPI_CLK, MBED_CONF_SD_SPI_CS);
uint8_t block[512] = "Hello World!\n";
int main()
{
    timer.start();
    // Call the SDBlockDevice instance initialisation method
    if (0 != sd.init()) {
        printf("Init failed \n");
        return -1;
    }
    printf("sd size: %llu\n",         sd.size());
    printf("sd read size: %llu\n",    sd.get_read_size());
    printf("sd program size: %llu\n", sd.get_program_size());
    printf("sd erase size: %llu\n",   sd.get_erase_size());
    // Set the frequency
    if (0 != sd.frequency(5000000)) {
        printf("Error setting frequency \n");
    }
    if (0 != sd.erase(0, sd.get_erase_size())) {
        printf("Error Erasing block \n");
    }
    // Write data block to the device
    if (0 == sd.program(block, 0, 512)) {
        // Read the data block from the device
        if (0 == sd.read(block, 0, 512)) {
            // Print the contents of the block
            printf("%s", block);
        }
    }
    // Call the SDBlockDevice instance de-initialisation method
    sd.deinit();
    timer.stop();
    printf("Done. It took: %d milliseconds\n", timer.read_ms());
    timer.reset();}
```

On the MAX32630FTHR it takes just 94 ms to run, while on the Artemis Thing Plus 12846 ms and on this board "Hello world!" is not prompted back in the terminal.

### PR DESCRIPTION
**Pull request by idea--list**
### Summary of changes 

Fixes #36 

Modified line 145:  previously the fill character has been hard coded to 0x00. However in Mbed OS core SPI_FILL_CHAR is defined in the core to be 0xFF by default (one can change that through mbed_app.json for example). This mod allows us to use the same fill character that is defined for Mbed OS.

Also modified spi_master_block_write(): previously it called am_hal_iom_blocking_transfer on line 182, but that prevented succesful SD card writing operations. Now i changed that part to am_hal_iom_spi_blocking_fullduplex and SD functionality seems to be working.

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [x] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by oclyke** [comment]
@idea--list nice catch. this looks good to me. right now we have two separate branches of this repo that need to be maintained (one that is up to date with mbed 6 and one that is still on mbed 5 for compatibility with the ArduinoBLE interface)

i'll ask @Wenn0101 to take a look at this PR and decide how best to integrate it.

**Comment by idea--list** [comment]
Did some power consumption tests with my PR. Interestingly the Artemis Thing Plus consumes about 33mA even if code execution has finished with the example code i posted in #36. After commenting out this part
```
if (0 == sd.read(block, 0, 512)) {
            // Print the contents of the block
            printf("%s", block);
        } 
```
power consumption normalizes to 6.6mA. Digging into `sd.read()` it turns out it also relies on `spi_master_block_write()` so will have to play around some more as with my current PR sd.read() does work but is too heavy on the battery. Hope i can come up with a better fix later this week.

**Comment by idea--list** [comment]
@oclyke and @Wenn0101
Edited spi_api.c file included in this PR. Functionality is retained and now also the power consumption gets low after the transaction is finished. 
Forgot to mention in the new commit, that i also got rid of `if (!Rw || (write_fill == 0x00))` as i do not see the point why would the fill character have any influence on the type of the SPI transaction, but i might be wrong.

**Comment by idea--list** [comment]
Meanwhile i made some tests with an eink display and a sensor that use SPI interface. Both seem to work fine with the PR, so i also sent the PR to the official Mbed repo.

**Comment by idea--list** [comment]
I close this topic as this PR has been merged into Mbed OS V6.5

**Pull request closed without merging**
